### ISSUE TITLE
Allow supersede of stuck low fee transaction with higher fee transaction

### ISSUE THREAD

**Issue by informatorius** [jdogresorg/freewallet#16]
When I try to send a transaction with low fee and it gets stuck then I want to be able to supersede that transaction with a higher fee transaction. 

Current workaround: Wait some days until transaction expires and retry with higher fee.

That usecase may become more popular because bitcoin fees get higher and you first want to try a low fee transaction to save fees. But if it gets stuck then a higher fee may be acceptable instead.

**Comment by jdogresorg** [comment]
This feature is called "replace-by-fee" and there is already an open issue for it #10 :)
