### ISSUE TITLE
Displaying address with over 1000 assets

### ISSUE THREAD

**Issue by cryptochainer** [jdogresorg/freewallet#17]
Freewallet does not display the entire contents of the address, and stops listing items at 1000.

**Comment by jdogresorg** [comment]
Need to update app to display first 1000, with option to click at bottom of list to load next 1000.

Don't want to load all balances everytime as balances are updated every few minutes.

**Comment by cryptochainer** [comment]
The new desktop app is amazing.  Adding the option to load the rest of the assets is an absolute, as having over 1000 assets is no longer only for the insane.

**Comment by jdogresorg** [comment]
Yeah, I’ll get to soon.

J-Dog
j-dog@j-dog.net
GPG : 0C85 9EE8 BC7D 0A56 055A  6D31 2411 DE07 1B00 02BF

**Comment by jdogresorg** [comment]
Issue fixed, but leaving open until next release

**Comment by jdogresorg** [comment]
Fixed in 0.9.7
