### ISSUE TITLE
Assets not being displayed in counterwallet

### ISSUE THREAD

**Issue by cryptochainer** [jdogresorg/freewallet#18]
Assets exist at address, but are not being displayed on counterwallet, or coindaddy's server.  Three show up, with incorrect balances, and the rest are not visible.  The assets are visible on rarepepewallet, xchain.io, etc.

**Comment by jdogresorg** [comment]
Are the assets showing up in freewallet?

**Comment by cryptochainer** [comment]
Yes, they do appear to be correct in freewallet.

**Comment by jdogresorg** [comment]
This repo is for reporting issues with Freewallet. If your having an issue with Counterwallet, please report it to the Counterwallet developers at https://github.com/CounterpartyXCP/counterwallet/issues
