### ISSUE TITLE
Automatically detect new versions and notify

### ISSUE THREAD

**Issue by jdogresorg** [jdogresorg/freewallet#2]
Need to add the ability for the app to automatically check for updates periodically and notify the user with a simple button click to update.

**Comment by jdogresorg** [comment]
add "Ignore" button with dropdown
- Ignore just release XXXX
- Ignore for the next week
- Ignore all releases

**Comment by informatorius** [comment]
"About FreeWallet" should show current version number too.

**Comment by jdogresorg** [comment]
good catch. will update the 'About' screen with the version number in the next release :)

**Comment by jdogresorg** [comment]
update notification system added with commit https://github.com/jdogresorg/freewallet-desktop/commit/c1f17b51c95131646c6e3cdcf929e9d2177998b1

**Comment by jdogresorg** [comment]
About screen updated 
![image](https://user-images.githubusercontent.com/376028/37380742-44b9a554-26f7-11e8-98a2-5f1f7c80ff2d.png)

**Comment by jdogresorg** [comment]
Fixed in 0.9.7
