### ISSUE TITLE
DEx interface headers print wrong in 1 direction of pairs

### ISSUE THREAD

**Issue by benchadwick** [jdogresorg/freewallet#26]
If you look at the DEx market you can find the order book for any pair by typing 'token1/token2' into the search bar. Pairs are also visible in the "opposite direction" for example 'token2/token1'. In this example I will show the BTC/XCP pair (or XCP/BTC)

If I search BTC/XCP you will see that the headers of the columns are

 "Date, Type, Price (XCP), Amount (BTC), Total (XCP)"

<img width="489" alt="btc xcp" src="https://user-images.githubusercontent.com/8106690/37571044-0918e5b6-2ace-11e8-9241-0adc08164911.png">

in this direction the headers, and the values under them are correct. In contrast if I search XCP/BTC the headers are

 "Date, Type, Price (BTC), Amount (XCP), Total (BTC)"

<img width="506" alt="xcp btc" src="https://user-images.githubusercontent.com/8106690/37571049-123e91f4-2ace-11e8-9dce-ec1f8a5ed202.png">

either the values in columns 4 and 5 need to be reversed or the headers need to be changed. Either way would work

**Comment by jdogresorg** [comment]
Thank you for reporting this issue. It turned out to be an issue with the xchain.io API calculating the price/amount on sell orders. This issue has been fixed with commit https://github.com/jdogresorg/XChain/commit/886ad27c3392dd113abb54f756ed6737406f2d20
