### ISSUE TITLE
support for data memos

### ISSUE THREAD

**Issue by cryptochainer** [jdogresorg/freewallet#27]
When sending funds, and entering in the memo/note field, it is too short to contain a SHA256 output, resulting in "Memo is too long" error.  In Counterwallet, if one selects "Data Memo" from the selections, the data is accepted.  This function may be useful for projects needing to verify the hash of images, or other files associated with blockchain assets.

**Comment by jdogresorg** [comment]
Thanks for the report. Will be fixed in v0.9.9.

![image](https://user-images.githubusercontent.com/376028/38217242-7d67fbea-3682-11e8-8786-5b83aa19be15.png)

 I'll leave this issue open until v0.9.9 is released.

**Comment by jdogresorg** [comment]
Should be fixed in most current release v0.9.10

https://github.com/jdogresorg/freewallet-desktop/releases/tag/v0.9.10
