### ISSUE TITLE
BTC Balance missing

### ISSUE THREAD

**Issue by jdogresorg** [jdogresorg/FreeWallet#4]
A couple users have reported that the BTC balance is missing entirely from their app... I believe issue is due to API calls to blockr.io failing due to expired SSL certificate.

Need to add secondary failover source for BTC balance to handle when primary API call fails.

**Comment by nickbretz** [comment]
This happened to me.   I can confirm it appears to be an API error to blockr.io from within the app.  

This is the error:    
"Looks like Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"

However if I manually run the request in a new browser tab, I get a success response with the correct data.   After that I took a step back and realized I had some privacy/ad blocking extensions loaded.   After disabled these, freewallet was able to make the request and bring in the BTC data into the app.

This is probably the issue the other users were having.

**Comment by jdogresorg** [comment]
Should be fixed with 8aca11031f828512c29158fdfd945f1a0343fde8
