### ISSUE TITLE
Forgotten password lock

### ISSUE THREAD

**Issue by Mouradch1971** [jdogresorg/freewallet#47]
Hi, can anyone assist on the above issue, I apparently forgot my lock password to fully access my wallet as you can see on the screenshot, how can I reset this password or bypass it? 
Thank you in advance.
Regards,
![Screen Shot 2020-05-29 at 13 17 27](https://user-images.githubusercontent.com/63730309/83258950-1dd3f400-a1af-11ea-81b2-1ab2b1dfa61d.png)

**Comment by jdogresorg** [comment]
As long as you have your 12-word passphrase written down somewhere (which you should), you should be fine.

You can click the icon in the upper right corner to log out of the wallet/reset it.

Then you can login using your 12-word passphrase, and your addresses will be accessible again without the need to remember that password. The wallet password is really just used in the local wallet to make sure no one other than you uses it.

J-Dog

**Comment by Mouradch1971** [comment]
Thank you so much JD, all done.
