### ISSUE TITLE
Wish for freewallet: When exchange is implemented also allow XCP/BTC automatically exchange without manual console BTCpay

### ISSUE THREAD

**Issue by informatorius** [jdogresorg/freewallet#8]
Wish for freewallet: When exchange is implemented also allow XCP/BTC automatically exchange without manual console BTCpay

**Comment by jdogresorg** [comment]
This is already on the feature list for the DEX Interface. You can see this of you download/install FreeWallet and click the "Exchange" tab.

![image](https://user-images.githubusercontent.com/376028/31578292-3f266720-b0d3-11e7-9485-0faaab29d6b6.png)

If you would like to see this feature be developed, please consider making a donation to support development :)
